#[build]
  base = "/letsmakemusic.netlify.app/"
#  base = ""
  publish = "/letsmakemusic.netlify.app/build-output/"
#  publish = ""

#[[redirects]]
#  from = "/*"
#  to = "/letsmakemusic.netlify.app/:splat"
#  status = 200
#  force = true
